# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pds/progressdialog_v3.ui'
#
# Created: Fri Sep 24 11:46:39 2010
#      by: PyQt4 UI code generator 4.7.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ProgressDialog(object):
    def setupUi(self, ProgressDialog):
        ProgressDialog.setObjectName(_fromUtf8("ProgressDialog"))
        ProgressDialog.resize(671, 453)
        self.gridLayout = QtGui.QGridLayout(ProgressDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(97, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(134, 132, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.animeLabel = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animeLabel.sizePolicy().hasHeightForWidth())
        self.animeLabel.setSizePolicy(sizePolicy)
        self.animeLabel.setMinimumSize(QtCore.QSize(100, 135))
        self.animeLabel.setText(_fromUtf8(""))
        self.animeLabel.setScaledContents(False)
        self.animeLabel.setWordWrap(False)
        self.animeLabel.setObjectName(_fromUtf8("animeLabel"))
        self.gridLayout.addWidget(self.animeLabel, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(133, 132, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(134, 161, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.actionLabel = QtGui.QLabel(ProgressDialog)
        self.actionLabel.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionLabel.setFont(font)
        self.actionLabel.setStyleSheet(_fromUtf8("color:white;"))
        self.actionLabel.setWordWrap(False)
        self.actionLabel.setObjectName(_fromUtf8("actionLabel"))
        self.verticalLayout_2.addWidget(self.actionLabel)
        self.progressBar = QtGui.QProgressBar(ProgressDialog)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.completedInfo = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completedInfo.sizePolicy().hasHeightForWidth())
        self.completedInfo.setSizePolicy(sizePolicy)
        self.completedInfo.setStyleSheet(_fromUtf8("color:white;"))
        self.completedInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.completedInfo.setWordWrap(True)
        self.completedInfo.setObjectName(_fromUtf8("completedInfo"))
        self.verticalLayout.addWidget(self.completedInfo)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self._2 = QtGui.QGridLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.operationInfo = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationInfo.sizePolicy().hasHeightForWidth())
        self.operationInfo.setSizePolicy(sizePolicy)
        self.operationInfo.setStyleSheet(_fromUtf8("color:white;"))
        self.operationInfo.setText(_fromUtf8(""))
        self.operationInfo.setWordWrap(False)
        self.operationInfo.setObjectName(_fromUtf8("operationInfo"))
        self._2.addWidget(self.operationInfo, 0, 1, 1, 1)
        self.timeLabel = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet(_fromUtf8("color:white;"))
        self.timeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setWordWrap(False)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self._2.addWidget(self.timeLabel, 2, 0, 1, 1)
        self.statusInfo = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusInfo.sizePolicy().hasHeightForWidth())
        self.statusInfo.setSizePolicy(sizePolicy)
        self.statusInfo.setStyleSheet(_fromUtf8("color:white;"))
        self.statusInfo.setWordWrap(False)
        self.statusInfo.setObjectName(_fromUtf8("statusInfo"))
        self._2.addWidget(self.statusInfo, 1, 1, 1, 1)
        self.timeRemaining = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRemaining.sizePolicy().hasHeightForWidth())
        self.timeRemaining.setSizePolicy(sizePolicy)
        self.timeRemaining.setStyleSheet(_fromUtf8("color:white;"))
        self.timeRemaining.setWordWrap(False)
        self.timeRemaining.setObjectName(_fromUtf8("timeRemaining"))
        self._2.addWidget(self.timeRemaining, 2, 1, 1, 1)
        self.operationLabel = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationLabel.sizePolicy().hasHeightForWidth())
        self.operationLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.operationLabel.setFont(font)
        self.operationLabel.setStyleSheet(_fromUtf8("color:white;"))
        self.operationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.operationLabel.setWordWrap(True)
        self.operationLabel.setObjectName(_fromUtf8("operationLabel"))
        self._2.addWidget(self.operationLabel, 0, 0, 1, 1)
        self.statusLabel = QtGui.QLabel(ProgressDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet(_fromUtf8("color:white;"))
        self.statusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self._2.addWidget(self.statusLabel, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._2.addItem(spacerItem6, 3, 0, 1, 2)
        self.horizontalLayout.addLayout(self._2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(134, 161, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 4, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(97, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 4, 2, 1, 1)
        self.cancelButton = QtGui.QPushButton(ProgressDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout.addWidget(self.cancelButton, 3, 2, 1, 1)

        self.retranslateUi(ProgressDialog)
        QtCore.QMetaObject.connectSlotsByName(ProgressDialog)

    def retranslateUi(self, ProgressDialog):
        ProgressDialog.setWindowTitle(QtGui.QApplication.translate("ProgressDialog", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLabel.setText(QtGui.QApplication.translate("ProgressDialog", "<h3>Preparing PiSi...</h3>", None, QtGui.QApplication.UnicodeUTF8))
        self.completedInfo.setText(QtGui.QApplication.translate("ProgressDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">-- / --, -- KB/s</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("ProgressDialog", "Time remaining:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusInfo.setText(QtGui.QApplication.translate("ProgressDialog", "--  / --", None, QtGui.QApplication.UnicodeUTF8))
        self.timeRemaining.setText(QtGui.QApplication.translate("ProgressDialog", "--:--:--", None, QtGui.QApplication.UnicodeUTF8))
        self.operationLabel.setText(QtGui.QApplication.translate("ProgressDialog", "Operation:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("ProgressDialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ProgressDialog", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setShortcut(QtGui.QApplication.translate("ProgressDialog", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))

